### ISSUE TITLE
Similar project for comparison

### ISSUE THREAD

**Issue by agsper** [hansel-reinhart/codex-amiatinus#3]
You may not be aware of another GitHub project by Andrew Dunning entitled Bede's Bible.  He has done an xml transcription of Codex Amiatinus that is complete in the New Testament, but apparently only Genesis is done in the Old Testament.  He now works at the Bodleian Library at Oxford UK and does not seem to have made any updates to his GitHub project since 12/2018.  I did an assessment of his transcription in the 4 gospels and noticed many errors that I called to his attention in 2018, but I do not think he has had the time to update the transcriptions.  (I believe his starting text was a digital Clementine Vulgate, based on my observations of the errors.)  You may find his transcription useful for digital comparison.  If you need to contact me: agsper@comcast.net.  I have currently set aside doing transcriptions of Amiatinus and Fuldensis to work on the Syriac Peshitta but would like to get back to Latin transcriptions again in the future as the Lord directs. I have previously done transcriptions of the Biblical text of most of the important Vetus Latina mss. of the New Testament and would like to compare them digitally with a critical (with variants) Vulgate text, with Amiatinus as a good place to start. Grace to you.

**Comment by hansel-reinhart** [comment]
> You may not be aware of another GitHub project by Andrew Dunning entitled Bede's Bible. He has done an xml transcription of Codex Amiatinus that is complete in the New Testament, but apparently only Genesis is done in the Old Testament. He now works at the Bodleian Library at Oxford UK and does not seem to have made any updates to his GitHub project since 12/2018. I did an assessment of his transcription in the 4 gospels and noticed many errors that I called to his attention in 2018, but I do not think he has had the time to update the transcriptions. (I believe his starting text was a digital Clementine Vulgate, based on my observations of the errors.) You may find his transcription useful for digital comparison. If you need to contact me: [agsper@comcast.net](mailto:agsper@comcast.net). I have currently set aside doing transcriptions of Amiatinus and Fuldensis to work on the Syriac Peshitta but would like to get back to Latin transcriptions again in the future as the Lord directs. I have previously done transcriptions of the Biblical text of most of the important Vetus Latina mss. of the New Testament and would like to compare them digitally with a critical (with variants) Vulgate text, with Amiatinus as a good place to start. Grace to you.

Thank you for your message, I'm glad you've taken an interest in the project and apologize that I haven't been more active. I did come across that project and was disappointed to see only Genesis and the New Testament complete. Was even more disappointed when using their Prologue to Genesis as a template for my own and finding numerous errors, so have since abandoned any of their resources, as not to taint mine.
Currently I have the Catholic Public Domain Version (2009) generated in uppercase, with U, J replaced with V, I, and a list of nomina sacras (codex-amiatinus/group-resources/20210727_nomina.txt) to make transcription a bit easier. I already have a private python script that auto-generates two versions from the file (codex-amiatinus/transcription/0000_full_codex.txt) into a true Codex Amiatinus and a formatted Codex Amiatinus (punctuation added, abbreviations expanded). These already generate full working bibles with the exception that the human manual transcription is only 35 pages in (time dedicated to other commitments) but with these tools, it should be picking up speed.
If you would ever like to contact me, don't hesitate to message me on Telegram at t.me/HenryReinhart

**Comment by agsper** [comment]
Hi Henry,

Thank you for taking the time to reply to my message.

I, too, had noted many errors in Andrew Dunning’s Bede’s Bible.  I compared his transcription with online photos and noted numerous errors in the 4 gospels.  I have attached his xml transcription as modified by me to correct the errors and to add some html tags to satisfy certain requirements for use of the transcription for an e-Sword Bible module.  Line breaks and indentations should be accurate and should make it easy to find the text in the online photos if any reading needs confirmation.  It may be of use to you.  I use KJV versification rather than Clementine because KJV is based on the original versification scheme of Stephanus 1555 Biblia Sacra Latina Vulgate ex Hebraicus (it seems to me unfortunate that the various language versions of the scriptures use slightly different numbering schemes).

I have not worked on Amiatinus for over a year, as I currently am working on reviewing a Peshitta transcription of the Hebrew Old Testament.  If, when, I get back to Latin I would like to complete my transcription of Codex Fuldensis gospels with markup giving verse numbers.

Andrew Sperlin
